version: "1"

services:
  swagger-ui:
    build:
      context: .
      dockerfile: ./DockerfileSwagger
    ports:
      - "8082:8082"
    restart: unless-stopped
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./swagger.json:/usr/share/nginx/html/swagger.json
  app:
    container_name: app_OnlineCinema
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    links:
      - db
    restart: unless-stopped
    networks:
      - postgres
  db:
    container_name: postgres_OnlineCinema
    image: postgres:16.2-alpine3.19
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "adminPG"
      POSTGRES_PASSWORD: "1Qwerty2$"
      POSTGRES_DB: "OnlineCinema"
    restart: unless-stopped
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres
  pgadmin:
    container_name: pgadmin_OnlineCinema
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@OnlineCinema.com"
      PGADMIN_DEFAULT_PASSWORD: "1Qwerty2$"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres
volumes:
  habrdb-data:
  pgadmin-data:
networks:
  postgres:
    driver: bridge